import { Inter } from "next/font/google";
import Navigation from "./(components)/Navigation.jsx";
import "./globals.css";
import AuthProvider from "../app/(components)/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background dark:bg-slate-800`}>
        <AuthProvider>
          <Navigation />
          <div className="m-2">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
